language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  only:
    - master
    - develop

after_success:
  - bash <(curl -s https://codecov.io/bash)
